import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    fontFamily: {
      sans: ['"Google Sans Flex"', "system-ui", "sans-serif"],
    },
    spacing: {
      0: "0px",
      px: "1px",
      1: "4px",
      1.5: "5px",
      2: "6px",
      2.5: "7px",
      3: "8px",
      4: "12px",
      5: "16px",
      6: "20px",
      7: "24px",
      8: "28px",
      9: "32px",
      10: "36px",
      11: "40px",
      12: "48px",
      13: "56px",
      14: "64px",
      15: "72px",
      16: "80px",
      17: "96px",
      18: "120px",
    },
    borderRadius: {
      none: "0px",
      1: "2px",
      "1.5": "3px",
      2: "4px",
      "2.5": "5px",
      3: "6px",
      4: "8px",
      "4.5": "9px",
      5: "10px",
      6: "12px",
      7: "14px",
      8: "16px",
      9: "18px",
      10: "20px",
      11: "24px",
      12: "32px",
      full: "9999px",
    },
    borderWidth: {
      DEFAULT: "1px",
      0: "0px",
      1: "0.5px",
      2: "1px",
      3: "1.5px",
      4: "2px",
      5: "2.5px",
      6: "4px",
    },
    boxShadow: {
      xs: "0px 2px 4px rgba(176, 175, 175, 0.16)",
      sm: "0px 4px 8px rgba(176, 175, 175, 0.20)",
      md: "0px 8px 16px rgba(176, 175, 175, 0.22)",
      lg: "0px 12px 24px rgba(176, 175, 175, 0.25)",
      none: "none",
    },
    fontSize: {
      // Label
      "label-xs": ["11px", { lineHeight: "16px", letterSpacing: "0.33px" }],
      "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.36px" }],
      "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.42px" }],
      "label-lg": ["16px", { lineHeight: "20px", letterSpacing: "0.32px" }],
      "label-xl": ["18px", { lineHeight: "24px", letterSpacing: "0.36px" }],
      "label-2xl": ["20px", { lineHeight: "24px", letterSpacing: "0.4px" }],
      // Body
      "body-xs": ["12px", { lineHeight: "16px", letterSpacing: "0.24px" }],
      "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.28px" }],
      "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0.16px" }],
      "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0.18px" }],
      "body-xl": ["20px", { lineHeight: "28px", letterSpacing: "0.2px" }],
      // Heading
      "heading-xs": ["20px", { lineHeight: "24px", letterSpacing: "0.2px" }],
      "heading-sm": ["24px", { lineHeight: "32px", letterSpacing: "0.24px" }],
      "heading-md": ["28px", { lineHeight: "36px", letterSpacing: "0.28px" }],
      "heading-lg": ["32px", { lineHeight: "40px", letterSpacing: "0.32px" }],
      "heading-xl": ["36px", { lineHeight: "44px", letterSpacing: "0px" }],
      "heading-2xl": ["40px", { lineHeight: "48px", letterSpacing: "0px" }],
      // Display
      "display-xs": ["48px", { lineHeight: "56px", letterSpacing: "-0.48px" }],
      "display-sm": ["60px", { lineHeight: "72px", letterSpacing: "-0.6px" }],
      "display-md": ["72px", { lineHeight: "84px", letterSpacing: "-0.72px" }],
    },
    fontWeight: {
      regular: "400",
      medium: "500",
      semibold: "600",
      bold: "700",
    },
    extend: {
      keyframes: {
        "hero-glow": {
          "0%, 100%": { opacity: "1", transform: "translate(-50%, -50%) scale(1)" },
          "50%": { opacity: "0.6", transform: "translate(-50%, -50%) scale(1.15)" },
        },
        "float-1": {
          "0%, 100%": { transform: "translateY(0) translateX(0)", opacity: "0.4" },
          "25%": { transform: "translateY(-20px) translateX(8px)", opacity: "0.7" },
          "50%": { transform: "translateY(-35px) translateX(-5px)", opacity: "0.3" },
          "75%": { transform: "translateY(-15px) translateX(12px)", opacity: "0.6" },
        },
        "float-2": {
          "0%, 100%": { transform: "translateY(0) translateX(0)", opacity: "0.5" },
          "33%": { transform: "translateY(-25px) translateX(-10px)", opacity: "0.3" },
          "66%": { transform: "translateY(-10px) translateX(15px)", opacity: "0.7" },
        },
        "float-3": {
          "0%, 100%": { transform: "translateY(0) translateX(0)", opacity: "0.3" },
          "20%": { transform: "translateY(-15px) translateX(10px)", opacity: "0.6" },
          "60%": { transform: "translateY(-30px) translateX(-8px)", opacity: "0.2" },
          "80%": { transform: "translateY(-8px) translateX(5px)", opacity: "0.5" },
        },
        "hero-fade-in": {
          from: { opacity: "0", transform: "translateY(24px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "ring-pulse": {
          "0%, 100%": { opacity: "0.5", transform: "scale(1)" },
          "50%": { opacity: "0", transform: "scale(1.08)" },
        },
        "logo-float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
        "specimen-float-1": {
          "0%, 100%": { transform: "translateY(0) translateX(0)" },
          "50%": { transform: "translateY(-12px) translateX(4px)" },
        },
        "specimen-float-2": {
          "0%, 100%": { transform: "translateY(0) translateX(0)" },
          "33%": { transform: "translateY(-16px) translateX(6px)" },
          "66%": { transform: "translateY(-6px) translateX(-4px)" },
        },
        "specimen-float-3": {
          "0%, 100%": { transform: "translateY(0) translateX(0)" },
          "40%": { transform: "translateY(-10px) translateX(-6px)" },
          "80%": { transform: "translateY(-4px) translateX(4px)" },
        },
        "aurora-drift-1": {
          "0%, 100%": { transform: "translate(0, 0) scale(1)" },
          "25%": { transform: "translate(30px, -20px) scale(1.05)" },
          "50%": { transform: "translate(-20px, 15px) scale(0.95)" },
          "75%": { transform: "translate(15px, 25px) scale(1.02)" },
        },
        "aurora-drift-2": {
          "0%, 100%": { transform: "translate(0, 0) scale(1)" },
          "33%": { transform: "translate(-25px, -15px) scale(1.08)" },
          "66%": { transform: "translate(20px, 10px) scale(0.92)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
        "gradient-rotate": {
          "0%": { "--gradient-angle": "0deg" },
          "100%": { "--gradient-angle": "360deg" },
        },
        "slide-up-fade": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "hero-glow": "hero-glow 6s ease-in-out infinite",
        "float-1": "float-1 7s ease-in-out infinite",
        "float-2": "float-2 9s ease-in-out infinite",
        "float-3": "float-3 11s ease-in-out infinite",
        "hero-fade-in": "hero-fade-in 0.8s ease-out both",
        "hero-fade-in-delay-1": "hero-fade-in 0.8s ease-out 0.15s both",
        "hero-fade-in-delay-2": "hero-fade-in 0.8s ease-out 0.3s both",
        "hero-fade-in-delay-3": "hero-fade-in 0.8s ease-out 0.45s both",
        "hero-fade-in-delay-4": "hero-fade-in 0.8s ease-out 0.6s both",
        "hero-fade-in-delay-5": "hero-fade-in 0.8s ease-out 0.75s both",
        "hero-fade-in-delay-6": "hero-fade-in 0.8s ease-out 0.9s both",
        "ring-pulse": "ring-pulse 3s ease-in-out infinite",
        "ring-pulse-delay": "ring-pulse 3s ease-in-out 1.5s infinite",
        "logo-float": "logo-float 4s ease-in-out infinite",
        "specimen-float-1": "specimen-float-1 8s ease-in-out infinite",
        "specimen-float-2": "specimen-float-2 10s ease-in-out infinite",
        "specimen-float-3": "specimen-float-3 12s ease-in-out infinite",
        "aurora-drift-1": "aurora-drift-1 15s ease-in-out infinite",
        "aurora-drift-2": "aurora-drift-2 20s ease-in-out infinite",
        shimmer: "shimmer 6s ease-in-out infinite",
        "gradient-rotate": "gradient-rotate 3s linear infinite",
        "slide-up-fade": "slide-up-fade 0.3s ease-out both",
      },
      colors: {
        // ── Primitive color palette ──
        primary: {
          10: "#f6f2ff",
          20: "#e8daff",
          30: "#d4bbff",
          40: "#be95ff",
          50: "#a56eff",
          60: "#8a3ffc",
          70: "#6929c4",
          80: "#491d8b",
          90: "#31135e",
          100: "#1c0f30",
        },
        neutral: {
          white: "#ffffff",
          10: "#f4f4f4",
          20: "#eaeaea",
          30: "#dbdbdb",
          40: "#c6c6c6",
          50: "#8d8d8d",
          60: "#6f6f6f",
          70: "#525252",
          80: "#393939",
          90: "#262626",
          100: "#161616",
          black: "#000000",
        },
        error: {
          10: "#fff1f1",
          20: "#ffd7d9",
          30: "#ffb3b8",
          40: "#ff8389",
          50: "#fa4d56",
          60: "#da1e28",
          70: "#a2191f",
          80: "#750e13",
          90: "#520408",
          100: "#2d0709",
        },
        success: {
          10: "#defbe6",
          20: "#a7f0ba",
          30: "#6fdc8c",
          40: "#42be65",
          50: "#24a148",
          60: "#198038",
          70: "#0e6027",
          80: "#044317",
          90: "#022d0d",
          100: "#071908",
        },
        warning: {
          10: "#fcf4d6",
          20: "#fddc69",
          30: "#f1c21b",
          40: "#d2a106",
          50: "#b28600",
          60: "#8e6a00",
          70: "#684e00",
          80: "#483700",
          90: "#302400",
          100: "#1c1500",
        },

        // ── Semantic tokens (light mode defaults, dark via CSS vars) ──
        background: "var(--color-background)",
        foreground: "var(--color-text-primary)",
        surface: {
          primary: "var(--color-surface-primary)",
          "primary-variant": "var(--color-surface-primary-variant)",
          secondary: "var(--color-surface-secondary)",
          "secondary-variant": "var(--color-surface-secondary-variant)",
          tertiary: "var(--color-surface-tertiary)",
          "tertiary-variant": "var(--color-surface-tertiary-variant)",
          inverse: "var(--color-surface-inverse)",
          elevated: "var(--color-surface-elevated)",
          brand: "var(--color-surface-brand)",
          critical: "var(--color-surface-critical)",
          success: "var(--color-surface-success)",
          warning: "var(--color-surface-warning)",
        },
        fill: {
          primary: "var(--color-fill-primary)",
          "primary-hover": "var(--color-fill-primary-hover)",
          "primary-active": "var(--color-fill-primary-active)",
          "primary-disabled": "var(--color-fill-primary-disabled)",
          "primary-variant": "var(--color-fill-primary-variant)",
          "primary-variant-disabled": "var(--color-fill-primary-variant-disabled)",
          secondary: "var(--color-fill-secondary)",
          "secondary-hover": "var(--color-fill-secondary-hover)",
          "secondary-active": "var(--color-fill-secondary-active)",
          tertiary: "var(--color-fill-tertiary)",
          "tertiary-hover": "var(--color-fill-tertiary-hover)",
          "tertiary-active": "var(--color-fill-tertiary-active)",
          "tertiary-disabled": "var(--color-fill-tertiary-disabled)",
          inverse: "var(--color-fill-inverse)",
          "inverse-hover": "var(--color-fill-inverse-hover)",
          "inverse-active": "var(--color-fill-inverse-active)",
          "inverse-disabled": "var(--color-fill-inverse-disabled)",
          elevated: "var(--color-fill-elevated)",
          "elevated-hover": "var(--color-fill-elevated-hover)",
          "elevated-active": "var(--color-fill-elevated-active)",
          brand: "var(--color-fill-brand)",
          "brand-hover": "var(--color-fill-brand-hover)",
          "brand-active": "var(--color-fill-brand-active)",
          "brand-secondary": "var(--color-fill-brand-secondary)",
          "brand-secondary-hover": "var(--color-fill-brand-secondary-hover)",
          "brand-secondary-active": "var(--color-fill-brand-secondary-active)",
          critical: "var(--color-fill-critical)",
          "critical-hover": "var(--color-fill-critical-hover)",
          "critical-active": "var(--color-fill-critical-active)",
          success: "var(--color-fill-success)",
          "success-hover": "var(--color-fill-success-hover)",
          "success-active": "var(--color-fill-success-active)",
          warning: "var(--color-fill-warning)",
          "warning-hover": "var(--color-fill-warning-hover)",
        },
        overlay: "var(--color-overlay)",

        // ── Semantic text colors (use as text-content-*) ──
        content: {
          primary: "var(--color-text-primary)",
          secondary: "var(--color-text-secondary)",
          tertiary: "var(--color-text-tertiary)",
          placeholder: "var(--color-text-placeholder)",
          disabled: "var(--color-text-disabled)",
          "primary-disabled": "var(--color-text-primary-disabled)",
          inverse: "var(--color-text-inverse)",
          brand: "var(--color-text-brand)",
          error: "var(--color-text-error)",
          success: "var(--color-text-success)",
          warning: "var(--color-text-warning)",
          "on-brand": "var(--color-text-on-brand)",
          "on-critical": "var(--color-text-on-critical)",
        },

        // ── Semantic border colors ──
        border: {
          DEFAULT: "var(--color-border-primary)",
          primary: "var(--color-border-primary)",
          secondary: "var(--color-border-secondary)",
          tertiary: "var(--color-border-tertiary)",
          "tertiary-hover": "var(--color-border-tertiary-hover)",
          "tertiary-disabled": "var(--color-border-tertiary-disabled)",
          inverse: "var(--color-border-inverse)",
          "inverse-hover": "var(--color-border-inverse-hover)",
          "inverse-active": "var(--color-border-inverse-active)",
          brand: "var(--color-border-brand)",
          critical: "var(--color-border-critical)",
          error: "var(--color-border-error)",
          success: "var(--color-border-success)",
          warning: "var(--color-border-warning)",
          focus: "var(--color-border-focus)",
          disabled: "var(--color-border-disabled)",
          "secondary-disabled": "var(--color-border-secondary-disabled)",
        },
      },
    },
  },
  plugins: [],
};

export default config;
